# Generated by Django 5.2.4 on 2025-09-03 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueentry',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='appointments.appointment'),
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='PatientProfile',
        ),
    ]
