# Generated by Django 5.2.4 on 2025-09-04 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_queueentry_appointment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QueueEntry',
        ),
    ]
