# Generated by Django 5.2.4 on 2025-09-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_queueentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
    ]
