# Generated by Django 5.2.4 on 2025-09-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_queue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queueentry',
            old_name='time_added',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='queueentry',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('completed', 'Completed')], default='waiting', max_length=20),
        ),
    ]
